services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    command: npm run serve:frontend
    container_name: frontend
    hostname: frontend
    env_file: ./apps/frontend/.env
    ports:
      - 4000:4000
    depends_on:
      - api
    networks:
      - ln-payments

  api:
    image: api
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    command: npm run serve:api
    container_name: api
    hostname: api
    env_file: ./apps/api/.env
    ports:
      - 3000:3000
    networks:
      - polar-network-1_default
      - ln-payments

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ln-payments-postgres:/var/lib/postgresql
      - ./utils/db/init:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - ln-payments

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  ln-payments-postgres:

networks:
  polar-network-1_default:
    external: true
  ln-payments:
